<TEXT>PROGRAM_TITLE,RoboScout - Stronghold 2016
<NUMBER>DEFAULT_WIDTH,450
<NUMBER>ASPECT_WIDTH,45
<NUMBER>ASPECT_HEIGHT,32
<IMAGE>PROGRAM_ICON,/images/icon.png
<TEXT>DEFAULT_RESOURCES,/default.res